# 06 — Python equivalents of OCPQ queries (subtasks f, g)

In [1]:
import sys, os
sys.path.insert(0, os.path.abspath('..'))
from olympic_transport.queries import _load, query_fi, query_fii, query_fiii, query_g, C, K

ocel = _load()

In [2]:
print(f'(f-i) TravelTickets with fare_class == "{C}"')
r1 = query_fi(ocel)
display(r1)

(f-i) TravelTickets with fare_class == "accredited"

       oid
0   T_0000
1   T_0002
2   T_0003
3   T_0004
4   T_0006
5   T_0007
6   T_0008
7   T_0009
8   T_0010
9   T_0014
10  T_0018
11  T_0020
12  T_0022
13  T_0025
14  T_0028
15  T_0030
16  T_0031
17  T_0032

In [3]:
print(f'(f-ii) fare_class=="{C}", 1× Board, 0× Validate')
r2 = query_fii(ocel)
display(r2)

(f-ii) fare_class=="accredited", 1× Board, 0× Validate

       oid
0   T_0000
1   T_0002
2   T_0003
3   T_0004
4   T_0006
5   T_0007
6   T_0008
7   T_0009
8   T_0010
9   T_0014
10  T_0018
11  T_0020
12  T_0022
13  T_0025
14  T_0030
15  T_0031
16  T_0032

In [4]:
print(f'(f-iii) GroupBookings with > {K} passengers')
r3 = query_fiii(ocel)
display(r3)

(f-iii) GroupBookings with > 2 passengers

  group_oid  n_passengers
0    GB_001             3
1    GB_004             3
2    GB_005             3
3    GB_006             3
4    GB_007             3
5    GB_009             4
6    GB_011             4

In [5]:
print('(g) Depart events with > 2 standard-fare passengers')
r4 = query_g(ocel)
display(r4)

(g) Depart events with > 2 standard-fare passengers

  depart_eid  n_standard_passengers
0     E_0090                      3